### PR TITLE
Various functions, enums, and type modification.

### PR DESCRIPTION
**Pull request by MikuAuahDark**
This is somewhat a big changes. These changes were made when I was making [Teal type definitions for LOVE](https://github.com/MikuAuahDark/love2d-tl), but I think it's useful to have some of the changes to upstream. Feel free to review and add comment, but I'll keep it in draft state until I completed it.

Progress:
* [x] Add `dpiscale` parameter to `love.graphics.newFont` 2nd and 3rd variants.
* [x] Move `Drawable` from `love` to `love.graphics`.
* [x] Move `ByteData` from `love` to `love.data`.
* [x] Add `DisplayOrientation` enum to `love.window`.
* [x] Add `DroppedFile` type to `love.filesystem`.
* [x] Add `Object` methods.
* [x] Add `VertexAttributeStep` enum to `love.graphics`.
* [x] Load `VertexWinding` enum in `love.graphics`.
* [x] Add `IndexDataType` enum to `love.graphics`.
* [x] Add `PixelFormat` enum to `love.image` (**partial**, some descriptions needs attention).
* [x] Add 2nd variant of `love.graphics.newShader`.
* [x] Add `love.font` module.
  * [x] `GlyphData` type and methods.
  * [x] `Rasterizer` type and methods.
  * [x] `HintingMode` enum.
  * [x] `love.font` functions.
* [x] Rename `Transform:isAffine` to `Transform:isAffine2DTransform`.
* [x] Move `CompressedDataFormat` from `love.math` to `love.data`.
* [x] Move `CompressedData` from `love.math` to `love.data`.
* [x] Add more constants to `CompareMode` enum.
* [x] Remove "already-removed" constants from `GraphicsFeature` enum.
* [x] Remove "canvasfsaa" constant from `GraphicsLimit` enum.
* [x] Add more `Texture` functions.
* [x] Remove duplication of various function in `Image` and `Canvas` which is available in `Texture`.
* [x] Rename `CanvasMipmapMode` to `MipmapMode`.

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
There are some problems
1. Some description for PixelFormat enum needs better description.
2. The HTML generator doesn't see `love.font` module for some reason.

**Comment by hahawoo** [comment]
Thank you! :) I left `love.font` out of the HTML generator because, as far as I knew at the time, these functions were used internally in LOVE's code but there wasn't a reason for a LOVE user to use them instead of `love.graphics.newFont` or `love.graphics.newImageFont`, but please let me know if I was mistaken!

**Comment by MikuAuahDark** [comment]
Looks like http://love2d-community.github.io/love-api/ is not updated yet after this merge.

**Comment by hahawoo** [comment]
Sorry @MikuAuahDark, I somehow didn't see your comment unti now. This project doesn't really seem to have an active maintainer, and I don't want to actively maintain it. Would you like to, or know anyone who would? :) I think updating the HTML page is simply a matter of running [html-generator.lua](https://github.com/love2d-community/love-api/tree/gh-pages/generator) and uploading the resulting page. And/or, would you like to maintain [loveref.github.io](https://loveref.github.io/)? It is basically the same but with a URL and a design that I prefer.

**Comment by MikuAuahDark** [comment]
Actually I have write access to this repo, but since I don't want to suddenly push lots of change without any discussion first, I made it as PR instead.

About loveref.github.io, I personally prefer the love2d-community.github.io/love-api style, although I think some text are simply too small, but that can be fixed by increasing the size of the text. I think automating the updates with GitHub Actions is possible, but I can't promise anything for the next 2 weeks.

**Comment by hahawoo** [comment]
Awesome, well if you find a way to automate the updates I'll do the same thing with loveref.github.io :)

Regarding making the text bigger, you might want to check out and merge PR #80

**Comment by hahawoo** [comment]
I'm not sure, I believe @rm-code and @daviel set this up.

While I can't say that I'm the "owner" of this repo (@rm-code again did the work for this, which I'm grateful for), you have my blessing (for what it's worth) @MikuAuahDark to automate and otherwise improve this project in any way you see fit (as does anyone else with write access to this repo).

**Comment by MikuAuahDark** [comment]
Well, I guess I'll wait for their replies first then. I don't want to mess up anything.

**Pull request merged**
