### PR TITLE
update for *some* 11.1 changes

### PR DESCRIPTION
**Pull request by flamendless**

### CODE REVIEW

**Comment by tst2005** [comment]
There is something wrong in your indentation at https://github.com/flamendless/love-api/blob/9d194926311e8a64ccd96d61d61fa4843d049376/modules/filesystem/Filesystem.lua#L166-L168

**Comment by flamendless** [comment]
I believe it's because of my vim config.

**Comment by rm-code** [comment]
I merged my branch for the 11.0 update just now.

@flamendless It would be cool if you could rebase against master again to get rid of any conflicts.

**Comment by flamendless** [comment]
@rm-code how? I havent done that before

**Comment by flamendless** [comment]
Would my modified code be gone?

**Pull request closed without merging**
