### PR TITLE
Updated config

### PR DESCRIPTION
**Pull request by davisdude**
- Added `externalstorage` flag.
- Updated descriptions

Some questions:
- Some descriptions (i.e. `window.width` and `height`, `window.minwidth` and `minheight`, and `window.x` and `y`) are used to describe both flags. How should that be handled?
- Some descriptions use newlines. How should these be handled (currently uses 2 newlines).
- Code format: `identity` uses a code block, and `version`, `window`, `window.minwidth`, `window.minheight`, `window.fullscreen`, `window.fullscreentype` all uses ```'s. How should these be represented (currently not).

### CODE REVIEW

**Comment by rm-code** [comment]
I think it would be fine to add two separate entries for window.width and height for example which simply contain the same description. I didn't have any use for the config part of the documentation in any of my plugins so far so it is hard to tell what makes sense and what doesn't.

Newlines are done via ```\n\n``` already. Should be the same for the config.

I wouldn't add the code block. Inline-Code parts can simply taken over without the ```. E.g.:

```
This ```foo``` does a lot of ```bar``` and everbody was like ```wooooo```.
```
Would simply become
```
This foo does a lot of bar and everbody was like wooooo.
```

That's how I've done it so far and it works well enough.

**Comment by rm-code** [comment]
Also looks like you forgot a ```}```
```
Error → specs/api_spec.lua @ 2
LÖVE-API Integrity test makes sure the api table is valid
specs/api_spec.lua:3: error loading module 'love_api' from file './love_api.lua':
	./love_api.lua:299: '}' expected (to close '{' at line 295) near 's'
Error → specs/api_spec.lua @ 7
LÖVE-API Integrity test checks that all values are of type string
specs/api_spec.lua:8: error loading module 'love_api' from file './love_api.lua':
	./love_api.lua:299: '}' expected (to close '{' at line 295) near 's'
Error → specs/api_spec.lua @ 23
LÖVE-API Integrity test makes sure only certain keys are used
specs/api_spec.lua:24: error loading module 'love_api' from file './love_api.lua':
	./love_api.lua:299: '}' expected (to close '{' at line 295) near 's'
Error → specs/api_spec.lua @ 73
LÖVE-API Integrity test checks each argument is wrapped in a table
specs/api_spec.lua:74: error loading module 'love_api' from file './love_api.lua':
	./love_api.lua:299: '}' expected (to close '{' at line 295) near 's'
Error → specs/api_spec.lua @ 92
LÖVE-API Integrity test checks each return value is wrapped in a table
specs/api_spec.lua:93: error loading module 'love_api' from file './love_api.lua':
	./love_api.lua:299: '}' expected (to close '{' at line 295) near 's'
```

**Comment by davisdude** [comment]
Okay, that seems fine.

**Comment by rm-code** [comment]
That looks good! Before I merge it would be cool if you could squash the commits so we have a clean history :)

Here's a good article on the topic:
http://eli.thegreenplace.net/2014/02/19/squashing-github-pull-requests-into-a-single-commit

**Comment by davisdude** [comment]
That's what I get for using the online editor! The string and text colors are so similar...

**Comment by rm-code** [comment]
Looks good :+1:

**Comment by rm-code** [comment]
Thanks :)

**Comment by davisdude** [comment]
No problem! :neckbeard:

**Pull request merged**
