### PR TITLE
Added ability to contain / (forward slash) in path

### PR DESCRIPTION
**Pull request by davisdude**

### CODE REVIEW

**Comment by rm-code** [comment]
@davisdude Which OS did you test this on?

@hahawoo IMO we can pull this, but I haven't tested it on my system yet.

**Comment by davisdude** [comment]
@rm-code Both Windows and Linux using Lua 5.2

**Comment by hahawoo** [comment]
Thanks @davisdude! My only question is: when would (...) contain slashes instead of dots? (I don't know much about this part of Lua, sorry!)

**Comment by davisdude** [comment]
Here's an example, where `test.lua` contains

```lua
print( ... )
```

And the directory structure is `./is/a/test.lua'

**Comment by davisdude** [comment]
I added a little more than I should have. Give me a second and I'll make squash everything into one commit.

**Comment by hahawoo** [comment]
I see, thanks for explaining that to me, I appreciate it.

**Comment by rm-code** [comment]
Thanks @davisdude 👍

**Pull request merged**
