### PR TITLE
Updated love.graphics.newImage

### PR DESCRIPTION
**Pull request by Aiq0**
Added missing `dpiscale` flag

### CODE REVIEW

**Comment by MikuAuahDark** [comment]
Any reason why the `ImageData` and `CompressedImageData` variant gets removed?

**Comment by Aiq0** [comment]
Not sure, but I think I just made it same as newCubeImage is, but I can re-add these variants

**Comment by MikuAuahDark** [comment]
Sure, please re-add them back. Also there's actually 6 images variant of newCubeImage.

**Comment by Aiq0** [comment]
Please look now, if it is ok

**Comment by MikuAuahDark** [comment]
If there are no more commits then I'll merge it in 5 minutes.

**Pull request merged**
